SELECT NB, NOM, PRENOM
FROM BUVEURS
WHERE NB IN(SELECT NB
		 FROM ACHATS A, VINS V
		 WHERE A.NV = V.NV
		 AND V.MILL = 1980)
AND NB NOT IN(SELECT NB
		   FROM A,V
		   WHERE A.NV = V.NV
		   AND V.MILL<>1980)

/
