--tpSQL2_1
select type
from buveurs
group by type
/

--tpSQL2_2
select * from vins
order by cru, mill desc
/

--tpSQL2_3
SELECT REGION
FROM PRODUCTEURS P, RECOLTES R, VINS V
WHERE P.NP = R.NP
AND R.NV = V.NV
AND (V.CRU = 'Pommard' OR V.CRU = 'Brouilly')
/

--tpSQL2_4
SELECT REGION
FROM PRODUCTEURS P,RECOLTES R,VINS V
WHERE P.NP = R.NP
AND R.NV = V.NV
AND V.CRU = 'Pommard'
AND EXISTS(SELECT *
		FROM P,R,V
		WHERE P.NP = R.NP
		AND R.NV = V.NV
		AND V.CRU = 'Brouilly')
/

--tpSQL2_5
SELECT SUM(QTE),CRU,MILL
FROM ACHATS A,VINS V
WHERE A.NV = V.NV
GROUP BY CRU,MILL
/

--tpSQL2_6
SELECT NV
FROM RECOLTES
GROUP BY NV
HAVING COUNT(NP)>3
/

--tpSQL2_7
SELECT *
FROM PRODUCTEURS
WHERE NP NOT IN (SELECT NP
		      FROM RECOLTES)
/

--tpSQL2_8_1
SELECT NB
FROM ACHATS A, VINS V
WHERE A.NV = V.NV
AND V.MILL = '1980'
GROUP BY NB
/

--tpSQL2_8_2
SELECT DISTINCT NB
FROM ACHATS A, VINS V
WHERE A.NV = V.NV
AND V.MILL = '1980'
/

--tpSQL2_9
SELECT DISTINCT NB
FROM BUVEURS B
WHERE NB NOT IN(SELECT NB
		     FROM ACHATS A, VINS V
		     WHERE A.NV = V.NV
		     AND V.MILL = 1980)
/

--tpSQL2_10
SELECT NB, NOM, PRENOM
FROM BUVEURS
WHERE NB IN(SELECT NB
		 FROM ACHATS A, VINS V
		 WHERE A.NV = V.NV
		 AND V.MILL = 1980)
AND NB NOT IN(SELECT NB
		   FROM A,V
		   WHERE A.NV = V.NV
		   AND V.MILL<>1980)
/
